import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/login');
  await page.getByRole('button', { name: 'Deny all' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('J');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('JAN');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('JAN.DE');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('JAN.DE.WIT+AI');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('JAN.DE.WIT+AI@NBN');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('JAN.DE.WIT+AI@NBN.');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('JAN.DE.WIT+AI@NBN.BE');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123a');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?@');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Search icon' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en ');
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('link', { name: 'English €160,00' }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'View shopping basket' }).click();
  await page.getByRole('link', { name: 'Remove' }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Remove' }).click();
  await page.getByRole('button', { name: 'Continue shopping' }).click();
  await page.getByRole('link', { name: 'NBN EN 1090-3:2019 ACTIVE' }).click();
});