import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/login');
  await page.getByRole('button', { name: 'Deny all' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('j');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn.');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn.be');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('AI');
  await page.getByRole('textbox', { name: 'Password' }).press('End');
  await page.getByRole('textbox', { name: 'Password' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Password' }).press('PageDown');
  await page.getByRole('textbox', { name: 'Password' }).press('NumLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?@');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Search icon' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090-4');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('link', { name: 'NBN EN 1090-4:2018 ACTIVE' }).click();
  await page.getByRole('link', { name: 'English' }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'View shopping basket' }).click();
  await page.getByRole('checkbox', { name: 'I\'ve read and agree to the' }).check();
  await page.getByRole('button', { name: 'Continue to checkout' }).click();
  await page.getByRole('button', { name: 'Bancontact' }).click();
  await page.getByRole('radio', { name: 'Paid' }).check();
  await page.getByRole('button', { name: 'Continue ›' }).click();
  await page.getByRole('button', { name: 'View my order history' }).click();
});