import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/login');
  await page.getByRole('button', { name: 'Deny all' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('j');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn.');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn.be');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').first().press('End');
  await page.getByRole('button').first().press('ArrowDown');
  await page.getByRole('button').first().press('PageDown');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI');
  await page.getByRole('textbox', { name: 'Password' }).press('End');
  await page.getByRole('textbox', { name: 'Password' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Password' }).press('PageDown');
  await page.getByRole('textbox', { name: 'Password' }).press('NumLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?@');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Search icon' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('link', { name: 'English €160,00' }).click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'View shopping basket' }).click();
  await page.getByText('Pay later (+€30 excl. VAT)').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('I\'ve read and agree to the').click();
  const page1 = await page1Promise;
  await page.getByRole('checkbox', { name: 'I\'ve read and agree to the' }).check();
  await page.getByRole('button', { name: 'Continue to checkout' }).click();
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/shop-redirect?ai_notification_sent=1&cs=30KKKWL17wTKx9q3ZgU5RG20tzxVw9uuM6Vf5gPGGJ9Rf4pUaE5TbZn5nkDne0gGt8Kk-l-PDrU4F_t2RMDXQbw');
});