import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/login');
  await page.getByRole('button', { name: 'Deny all' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn.be');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?@');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Order history View your order' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Invoice' }).nth(3).click();
  const download = await downloadPromise;
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Invoice' }).first().click();
  const download1 = await download1Promise;
  await page.getByText('Invoice with fee service fee').first().click();
  await page.getByText('Total €').first().click();
  await page.getByText('NBN NBN EN 76 ACTIVE Packages').nth(1).click();
  await page.locator('div:nth-child(28)').click();
});