import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/login');
  await page.getByRole('button', { name: 'Deny all' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('jan.de.wit+ai@nbn.be');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').first().click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('AI123Ai12345678?@');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'NBN EN 1090-4:2018 PUBLISHED' }).click();
  await page.getByRole('link', { name: 'Search icon' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn');
  await page.getByRole('textbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en ');
  await page.getByRole('textbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090_4');
  await page.getByRole('textbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090-\'');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('link', { name: 'NBN EN 1090-4:2018 ACTIVE' }).click();
  await page.goto('https://app-qa.nbn.be/data/r/platform/frontend/home');
  await page.getByRole('link', { name: 'Search icon' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090-');
  await page.getByRole('textbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search' }).fill('nbn en 1090-4');
  await page.getByRole('textbox', { name: 'Search' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.getByRole('link', { name: 'French', exact: true }).click();
  const page1Promise = page.waitForEvent('popup');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Download' }).click();
  const page1 = await page1Promise;
  const download = await downloadPromise;
});